version: '2'

services:
  dercy-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: dercy:latest
    ports:
      - "5000:5000"
    environment:
      POSTGRESQL_HOST: "db"
      POSTGRESQL_PORT: "5432"
    networks:
      - dercy-net
    depends_on: 
      - db
  db:
    # build:
    #   context: ../
    #   dockerfile: docker/postgresql.Dockerfile
    # image: psql-custom:latest
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./dercypy/static/data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "gustavo"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
      PGPASSWORD: "test"
    networks:
      - dercy-net
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
    networks:
      - dercy-net
  
networks:
  dercy-net:
    driver: bridge
